### ISSUE TITLE
Backward compatibility with R 4.02

### ISSUE THREAD

**Issue by 3SMMZRjWgS** [msperlin/yfR#4]
@msperlin 

Thank you for creating this package! I've read your blog post about it and I have used your other package BatchGetSymbols for a while. When I tried to install yfR:: via Github, I get an error message about yfR:: requires R 4.1 or greater. Is there any chance that this package can be made backward compatible to R 4.0.2. The reason being that's the most recent version used in Microsoft R Open, which I suspect is still a reasonably popular R distribution that others are using for its MKL acceleration capabilities. 

Thanks for considering the request!

**Comment by msperlin** [comment]
Good morning, 

Your request makes sense. I'll match it to a minimum of R 4.0.0 before sending to CRAN. 
However, this will takes some time as the package is under review in [ropensci](https://github.com/ropensci/software-review/issues/523) and I don't want to implement changes while the review is active.

**Comment by 3SMMZRjWgS** [comment]
Thank you granting this request, @msperlin! No rush in terms of timing, BatchGetSymbols still works amazingly well thanks to your efforts!
