### ISSUE TITLE
Error in download

### ISSUE THREAD

**Issue by DanielleKarling** [msperlin/yfR#8]
I'm getting an error in downloads when running the sample code.

what am I doing wrong?

![image](https://user-images.githubusercontent.com/88064289/168443915-63a5c39d-fa09-4fcb-96cc-516f275d5679.png)

**Comment by DanielleKarling** [comment]
I'd exceeded the yahoo finances request limit

**Comment by msperlin** [comment]
Yes, thats true. Soon I'll implement something to let users know about the limit (and wheter a execution has reached it).

**Comment by ishonest** [comment]
@msperlin is this resolved?

**Comment by msperlin** [comment]
@ishonest  Yes and no. The initial issue with quantmod::getsymbols was fixed. But, we are still figuring out how to deal with the YF api limit. 

See this thread:

https://github.com/joshuaulrich/quantmod/issues/360#issuecomment-1133969838  

nonetheless, I'll reopen this issue.

**Comment by msperlin** [comment]
Fixed in 584c21959369064ad6fffe23a1444392e3c6cfc9

**Comment by msperlin** [comment]
Added quantmod version requirement.
